### ISSUE TITLE
numpy 2 compatibility

### ISSUE THREAD

**Issue by manthey** [ImagingDataCommons/dicomweb-client#100]
It would be great were compatible with numpy >= 2.  It looks like the only change would be to convert `np.prod` to `math.prod`, though `math.prod` is a Python >= 3.8 feature, so if 3.7 compatibility is still desired, it could be changed to `(math.prod if hasattr(math, 'prod') else np.prod)`.  There are two instances in file.py.

**Comment by pieper** [comment]
That sounds reasonable.  Can you make a PR?

**Comment by manthey** [comment]
> That sounds reasonable. Can you make a PR?

Thanks @pieper .  See #101.
