### ISSUE TITLE
[Doc] Broken link in "Introduction"

### ISSUE THREAD

**Issue by Zaelot** [ImagingDataCommons/dicomweb-client#80]
The link to the standard itself is wrong/old (resulting in 404):
http://www.dicomstandard.org/dicomweb/
(I guess it should be: https://www.dicomstandard.org/current/ )

Found on:
https://dicomweb-client.readthedocs.io/en/latest/introduction.html

**Comment by hackermd** [comment]
Thank you for reporting the issue @Zaelot. It appears the location of the website has changed. It is now located at https://www.dicomstandard.org/using/dicomweb.
