### ISSUE TITLE
Provide the results as Iterable of generators instead of lists

### ISSUE THREAD

**Issue by medihack** [ImagingDataCommons/dicomweb-client#88]
When returning `Iterable`s by the DICOMwebClient methods that are created by a `Generator` instead of lists, it would be possible to process the results of each method on the fly (maybe in another thread or process).

**Comment by vanossj** [comment]
There are `iter_` versions for the `retrieve_` methods. eg, [`iter_series`](https://dicomweb-client.readthedocs.io/en/latest/package.html#dicomweb_client.api.DICOMfileClient.iter_series) and [`retrieve_series`](https://dicomweb-client.readthedocs.io/en/latest/package.html#dicomweb_client.api.DICOMfileClient.retrieve_series).

The `iter_` methods should stream the results back if the server supports it.

**Comment by medihack** [comment]
Thanks a lot. I somehow overlooked your answer, but that is what I was looking for. Thanks again and I am closing this issue.
